server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:loansDB
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

build:
  version: "2.0"

loans:
  message: "Welcome to Guts bank Cards Local APIs"
  email_name:
    name: "Guts - Developer"
    email: "gutsblackswordsman96@gmail.com"
  mobile_number:
    - (111)345-3246
    - (111)345-4543

